如果採用，此提交將更新目錄架構與新增C語言
we684123/Atom_packages pull request #4
Opened 2021-03-26 02:27 UTC by timmy61109

新增C語言相關套件說明，目前只是簡單的新增，後續會繼續更新。

2021-04-07 05:18 UTC, we684123 commented
那個... 抱歉
但可以請你說一下為何在 [other](https://github.com/timmy61109/Atom_packages/#other) 跟 [tool](https://github.com/timmy61109/Atom_packages/#tool) 有一樣的內容嗎?
想請問這樣的好處是?

2021-04-13 02:00 UTC, timmy61109 commented
> @timmy61109
> 那個... 抱歉
> 但可以請你說一下為何在 [other](https://github.com/timmy61109/Atom_packages/#other) 跟 [tool](https://github.com/timmy61109/Atom_packages/#tool) 有一樣的內容嗎?
> 想請問這樣的好處是?

抱歉，我忘記改到，我已經修改好了，請看一下可不可以。

2021-04-18 18:15 UTC, JackLKC requested changes
繁體

2021-04-19 04:43 UTC, timmy61109 commented
有部份內容不是繁體，這部份就等我一一測試完成後就可以改為繁體，這份原始為 @we684123 ，因此需要再調整。

2021-04-19 07:07 UTC, we684123 commented
@timmy61109 謝謝您！

2021-04-19 07:07 UTC, we684123 commented
@timmy61109 謝謝您！

2021-04-19 07:07 UTC, merged